Default: &defaults
  user: haffen
  password: haffen
  host: localhost
  port: 27017
  database: haffen
  poolsize: 10

Development:
  <<: *defaults

Test:
  database: haffen_test
  <<: *defaults

Staging:
  database: haffen_staging
  poolsize: 100
  <<: *defaults

Production:
  database: haffen_production
  poolsize: 100
  <<: *defaults